CREATE TABLE PERSONALSCHEDULE_TBL
(
    SD_UNIQUE_NUMBER INT AUTO_INCREMENT PRIMARY KEY, /*고유번호*/
    SCHEDULE         VARCHAR(2000) NOT NULL, /*일정*/
    SD_NAME          VARCHAR(50)   NOT NULL, /*작성자*/
    SD_PASSWORD      VARCHAR(50)   NOT NULL, /*비밀번호*/
    SD_REGDATE       TIMESTAMP     NULL DEFAULT CURRENT_TIMESTAMP, /*작성일자*/
    SD_MODIFYDATE    TIMESTAMP     NULL DEFAULT CURRENT_TIMESTAMP /*수정일자*/
);
